### ISSUE TITLE
Error on starting yayagram.service

### ISSUE THREAD

**Issue by Ventosinos** [mrcatacroquer/Yayagram#2]
Hi, I'm building a yayagram, (thank you so much, its awesome) and I think that I found an error on the last step of the "Creating the Systemd service".
The code says
sudo systemctl enable **example**.service

but I think it should be
sudo systemctl enable **yayagram**.service

Hope that it helps!

**Comment by mrcatacroquer** [comment]
Thank you!

I fixed it here: https://github.com/mrcatacroquer/yayagram/commit/c40bf52222e6adf9f7731c416987650b0b42eaec

I hope your Yayagram make is going fine!

**Comment by Ventosinos** [comment]
Happy to contribute!

I have just finished to build it. I made some modifications on it, because my Yaya has arthritis and it would be difficult for her to plug the cable on the holes.

I solved it using buttons and leds to indicate the selected receiver. I am new on github, so if you want me to send the modifications, please tell me how should I do it.

Thank you so much for creating such an amazing thing!

Jacobo Ventosinos
________________________________
